name: Autograding (local preview)

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-autograding:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show autograding.json (debug)
        run: |
          echo "Commit: $GITHUB_SHA"
          echo "Listing .github/classroom:"
          ls -la .github/classroom || true
          echo "----- BEGIN autograding.json -----"
          cat .github/classroom/autograding.json
          echo "----- END autograding.json -----"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Autograding
        uses: education/autograding@v1
        with:
          path: .github/classroom/autograding.json
