name: Classroom Autograding
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  autograding:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Classroom Autograding
        uses: education/autograding@v1
